name: devboard-ic

services:
  devboard-mcp:
    build:
      context: .
    container_name: devboard-mcp
    restart: unless-stopped
    env_file: .env
    ports:
      - "18009:8000"
    networks:
      - devboard-ic-network

networks:
  devboard-ic-network:
    name: devboard-ic-network
    external: true
